/** Clés de cache TanStack Query, toujours préfixées par la boutique active (docs/PLAN-CODE.md §6.7). */
export const qk = {
  store: (store: string) => ['store', store, 'current'] as const,
  overview: (store: string, period: string) => ['store', store, 'reporting', period] as const,
  products: (store: string) => ['store', store, 'products'] as const,
  productList: (store: string, filters: object) => ['store', store, 'products', 'list', filters] as const,
  product: (store: string, id: string) => ['store', store, 'products', 'detail', id] as const,
  brands: (store: string) => ['store', store, 'brands'] as const,
  brandList: (store: string, filters: object) => ['store', store, 'brands', 'list', filters] as const,
  collections: (store: string) => ['store', store, 'collections'] as const,
  collectionList: (store: string, filters: object) => ['store', store, 'collections', 'list', filters] as const,
  collection: (store: string, id: string) => ['store', store, 'collections', 'detail', id] as const,
  orders: (store: string) => ['store', store, 'orders'] as const,
  orderList: (store: string, filters: object) => ['store', store, 'orders', 'list', filters] as const,
  order: (store: string, id: string) => ['store', store, 'orders', 'detail', id] as const,
  customers: (store: string) => ['store', store, 'customers'] as const,
  customerList: (store: string, filters: object) => ['store', store, 'customers', 'list', filters] as const,
  customer: (store: string, id: string) => ['store', store, 'customers', 'detail', id] as const,
  inventory: (store: string, filter: string) => ['store', store, 'inventory', filter] as const,
  inventoryList: (store: string, filters: object) => ['store', store, 'inventory', 'list', filters] as const,
  movements: (store: string, variantId: string) => ['store', store, 'inventory', 'movements', variantId] as const,
  campaigns: (store: string) => ['store', store, 'campaigns'] as const,
  site: (store: string) => ['store', store, 'site'] as const,
};
